name: lienol-1907

on:
  push:
    branches:
      - master
    paths:
      - '.config'
  schedule:
    - cron: 0 8 * * *
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          
    - name: Clone source code
      env: 
        REPO_URL: https://github.com/Lienol/openwrt
        REPO_BRANCH: dev-19.07
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
      
    - name: Clone Config
      env: 
        REPO_URL: https://github.com/silmace/Lienol-Openwrt-Newifi3
      run: git clone --depth 1 $REPO_URL openwrt-config
    
    - name: Custom feeds file
      run: |
          cd openwrt
          rm -rf feeds.conf.default
          cp ../openwrt-config/feeds feeds.conf.default
      
    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a
    
    - name: Custom configure file
      run: |
          cd openwrt
          sed -i 's/192.168.1.1/192.168.123.1/g' package/base-files/files/bin/config_generate
          sed -i 's/OpenWrt/newifi3/g' package/base-files/files/bin/config_generate
          sed -i 's/luci-theme-bootstrap/luci-theme-argon_new/g' feeds/luci/collections/luci/Makefile
          rm -f .config
          cp ../openwrt-config/.config .config
   
    - name: Make Defconfig
      run: |
          cd openwrt
          make defconfig
    - name: Make download
      run: |
          cd openwrt
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
    - name: Multi-thread compile
      run: |
          cd openwrt
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s
    - name: Single-thread compile
      if: failure()
      run: |
          cd openwrt
          make -j1 V=s
   
    - name: Upload firmware to cowtransfer
      run: |
        rm -rf ./artifact/
        mkdir -p ./artifact/
        find openwrt/bin/targets/ -name "*sysupgrade*bin*" | xargs -i mv -f {} ./artifact/
        find openwrt/bin/targets/ -name "*combined*img*" | xargs -i mv -f {} ./artifact/
        cp openwrt/.config ./artifact/
        curl -fsSL git.io/file-transfer | sh
        ./transfer cow --block 2621440 -s --no-progress ./artifact/ 2>&1 | tee cowtransfer.log
        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
